services:
  - type: web
    name: catalogo-colonias
    env: python
    runtime: python-3.11.0
    buildCommand: "pip install -r requirements.txt && python cargar_datos.py"
    startCommand: "gunicorn prueba:app"
    plan: free
